### ISSUE TITLE
The Event Router doesn't get events from VCSA

### ISSUE THREAD

**Issue by it-podshivalov** [vmware-samples/vcenter-event-broker-appliance#716] opened 2021-11-08 05:28 UTC
Hello Friends!

VEBA v0.7.0
VCSA v6.7U3o

I have a problem with my VEBA.The Event Router doesn't get events from the VCSA.
I'm sure, login\password is correct and user for veba has administration permissions on vcsa.

_kubectl get pods -A_
![изображение](https://user-images.githubusercontent.com/57752592/140688511-087ceb9e-bd63-4bc8-b9e3-b3057500c129.png)

_kubectl -n vmware-system logs vmware-event-router-vcenter-f5dd944c6-kqqh6 | less_
![изображение](https://user-images.githubusercontent.com/57752592/140688267-b8da9d0a-72b7-4d6b-87a8-c787683b9394.png)

This is a tcpdump running on an esxi where is the vcsa.  
10.61.202.48 - veba
10.61.202.4 - vcsa
_pktcap-uw --switchport 83889104 --dir 2 --ip 10.61.202.4 -o - | tcpdump-uw -enr - | grep 10.61.202.48_
![изображение](https://user-images.githubusercontent.com/57752592/140688430-7190abf9-09aa-43a0-865b-1dbdad20379d.png)

Please help)

**Comment by embano1** [comment] 2021-11-08 13:42
Hi @it-podshivalov 

Thx for reporting this! I heard of one case where the underlying `govmomi` SOAP transport would never be able to retrieve events from vCenter, which we could not yet figure out (user did not get back to us).

First step would be to enable `DEBUG` mode of the event router, which can be done by changing (editing) the router deployment. the flag `"-log-level", "info"` must be changed to "-log-level", "debug".

**Comment by it-podshivalov** [comment] 2021-11-09 03:47
Hi dear @embano1
I changed the log level. 

Now I see it-
![изображение](https://user-images.githubusercontent.com/57752592/140856962-5f6e2467-6736-466c-be6b-62e963319eb9.png)

I'm sure, there are very much events in VCSA, because that is not small installation.

I want to note. I have 3 more VCSA, they all (including our problem-VCSA) are united in Linked Mode, and all have same version. However, they have also VEBA installation and it works fine.

**Comment by embano1** [comment] 2021-11-09 15:20
Thx for the details, this looks exactly like the same issue reported by another user. Back then, we did a lot of troubleshooting and the issue is not VEBA. We used the underlying `govmomi` APIs directly and even there could not get any events from a particular VC (also in linked mode).

Since this is not a VEBA issue, may I ask you to raise a support ticket with VMware describing that the `EventHistoryCollector` SOAP APIs are not returning events for a particular vCenter running in linked mode? Feel free to drop my name in the ticket so I can work with the support engineers.

**Comment by it-podshivalov** [comment] 2021-11-10 05:24
I created the support request, and added your email in copy.

**Comment by it-podshivalov** [comment] 2021-11-11 05:32
It turned out that another VCSA in the same Linked Mode has the same problem. As a result, two VCSA do not give events and two works fine.

**Comment by embano1** [comment] 2021-11-11 11:56
Thx, this is exactly the same issue as reported by another user (4 VCs in linked mode, 2 don't emit events). This needs to go through VMware support.

**Comment by it-podshivalov** [comment] 2021-11-17 08:06
Hi @embano1 
Can you check mail please

**Comment by embano1** [comment] 2021-11-17 08:16
@it-podshivalov can you please reach out via veba email so we can sync up further? See bottom of this page for details: https://vmweventbroker.io/community

**Comment by it-podshivalov** [comment] 2022-01-10 04:05
Hi @embano1 


This is a last answer from support VMware - 

<<
Alexey, hello.
Unfortunately, we do not provide support for the veba product, respectively, we do not have accurate information on the location of its logs.
https://vmweventbroker.io/faq

From the vCenter side, unfortunately, we do not see the reason for not receiving events. There is an active session on the side of the veba account and an event collector has been created:
--> /--> /Session Start/Session Pool/Session/Id='5273dd93-8d54-65a6-5ee7-3348af6743c0'/Username='VSPHERE.LOCAL\web'/Client IP='10.61.202.48'/EventCollector/NumEvents/total 10
There are also no problems on the vCenter side when displaying events for entities, respectively, it is most likely that there is a problem at the veba level.
Please continue to diagnose the problem on the part of veba

With respect,
Andrey Runge
Global Support Services, VMware Inc.
>>

Does this look like the end?((

**Comment by embano1** [comment] 2022-02-15 07:33
Closing as this is a known issue in vCenter. Please raise with VMware support.

**Closed** 2022-02-15 07:33 UTC
